live: false
source: sqlite
timeframe: 30s
cache_db: /mnt/data/combined_cache_30s_ENA_2026-02-01_2026-03-01.db
portfolio:
  initial_equity_per_leg: 100.0
  fee_rate: 0.0005
  slippage_per_side: 0.0
  max_notional_frac: 1.0
strategy_class_long: strategies.cryptomine_pack_dual_full.CryptomineLongPackAdaptiveEven
strategy_class_short: strategies.cryptomine_pack_dual_full.CryptomineShortPackAdaptiveEven
strategy_params_long:
  firstBuyQtyCoin: 0.0
  minOrderQtyCoin: 1000000000.0
  minOrderUSDT: 1000000000000.0
  useEquityPctBase: true
  baseOrderPctEq: 0.6
  equityForSizingUSDT: 300.0
  tpPercent: 0.25
  callbackPercent: 0.060000000000000005
  marginCallLimit: 244
  linearDropPercent: 0.19
  autoMerge: false
  subSellTPPercent: 0.44
  requireCloseAboveFullTP: true
  subSellCloseConfirmMode: breakeven
  requireCloseBelowDcaLevel: true
  blockDcaOnTpTouch: false
  drop1: 0.3
  drop2: 0.4
  drop3: 0.6
  drop4: 0.8
  drop5: 0.8
  mult2: 1.7
  mult3: 1.0
  mult4: 2.0
  mult5: 3.5
  maxFillsPerBar: 6
  maxSubSellsPerBar: 10
  useHighLowTouch: true
  useLiveSyncStart: false
  liveStartTime: 0
  maxOrdersPer3Min: 14
  useTrendAdaptiveSizing: true
  trendMaTf: W
  trendMaLen: 20
  trendSlopeBars: 3
  trendSlopeLongBoundPct: 1.0
  trendSlopeShortBoundPct: -1.0
  trendScoreMinPct: 45.0
  trendScoreMaxPct: 75.0
  minLongInvestPct: 0.5
  maxLongInvestPct: 2.2
  hardBreakevenDeleveragePct: 50.0
strategy_params_short:
  firstSellQtyCoin: 0.09
  minOrderQtyCoin: 0.09
  useEquityPctBase: true
  baseOrderPctEq: 1.0
  equityForSizingUSDT: 300.0
  tpPercent: 0.1
  callbackPercent: 0.22
  marginCallLimit: 244
  linearRisePercent: 0.3
  autoMerge: false
  subSellTPPercent: 0.15
  requireCloseBelowFullTP: true
  subCoverCloseConfirmMode: breakeven
  requireCloseAboveDcaLevel: true
  blockDcaOnTpTouch: false
  rise1: 0.28
  rise2: 0.4
  rise3: 0.6
  rise4: 0.8
  rise5: 0.8
  mult2: 1.6
  mult3: 1.0
  mult4: 2.0
  mult5: 3.5
  maxFillsPerBar: 6
  maxSubSellsPerBar: 10
  useHighLowTouch: true
  useLiveSyncStart: false
  liveStartTime: 0
  maxOrdersPer3Min: 14
  useTrendAdaptiveSizing: true
  trendMaTf: W
  trendMaLen: 20
  trendSlopeBars: 3
  trendSlopeLongBoundPct: 1.0
  trendSlopeShortBoundPct: -1.0
  trendScoreMinPct: 45.0
  trendScoreMaxPct: 75.0
  minShortInvestPct: 0.4
  maxShortInvestPct: 0.8
  hardBreakevenDeleveragePct: 70.0
