live: false
source: sqlite
timeframe: 0.5m
cache_db: combined_cache_30s_ENA_2026-02-01_2026-03-01.db
portfolio:
  initial_equity_per_leg: 100.0
  fee_rate: 0.0005
  slippage_per_side: 0.0
  max_notional_frac: 1.0
<<<<<<< HEAD
strategy_class_long: strategies.cryptomine_c_limit14_even_dual.CryptomineCLimit14LongEven
strategy_class_short: strategies.cryptomine_c_limit14_even_dual.CryptomineCLimit14ShortEven
=======
  position_notional_long: 2
  position_notional_short: 2
strategy_class_long: strategies.cryptomine_c_limit14_even_dual_1.CryptomineCLimit14LongEven
strategy_class_short: strategies.cryptomine_c_limit14_even_dual_1.CryptomineCLimit14ShortEven
>>>>>>> a
strategy_params_long:
  tpPercent: 0.25999999999999995
  callbackPercent: 0.28
  marginCallLimit: 244
  linearDropPercent: 0.14
  autoMerge: false
  subSellTPPercent: 0.36000000000000004
  drop1: 0.3
  drop2: 0.4
  drop3: 0.6
  drop4: 0.8
  drop5: 0.8
  mult2: 1.5
  mult3: 1.0
  mult4: 2.0
  mult5: 3.5
  maxFillsPerBar: 6
  maxSubSellsPerBar: 10
  signalsThrottleEnabled: false
  useEvenBars: true
  useLiveSyncStart: false
  slEnabled: false
  maxBudgetFrac: 0.6
  stopPercent: 99.0
  firstBuyUSDT: 3.5
  requireCloseAboveFullTP: true
  subSellCloseConfirmMode: breakeven
  requireCloseBelowDcaLevel: true
  blockDcaOnTpTouch: false
  useHighLowTouch: true
  maxOrdersPer3Min: 14
strategy_params_short:
  tpPercent: 0.21999999999999997
  callbackPercent: 0.41000000000000003
  marginCallLimit: 244
  linearRisePercent: 0.03
  autoMerge: false
  subSellTPPercent: -0.01
  rise1: 0.3
  rise2: 0.4
  rise3: 0.6
  rise4: 0.8
  rise5: 0.8
  mult2: 1.5
  mult3: 1.0
  mult4: 2.0
  mult5: 3.5
  maxFillsPerBar: 6
  maxSubSellsPerBar: 10
  signalsThrottleEnabled: false
  useEvenBars: true
  useLiveSyncStart: false
  slEnabled: false
  maxBudgetFrac: 0.6
  stopPercent: 99.0
  firstSellUSDT: 17.0
  requireCloseBelowFullTP: true
  subCoverCloseConfirmMode: breakeven
  requireCloseAboveDcaLevel: true
  blockDcaOnTpTouch: false
  useHighLowTouch: true
  maxOrdersPer3Min: 14
