timeframe: "5m"
cache_db: combined_cache_5m_5000_04.09.db #combined_cache_5m_5000_01.09.db #combined_cache_5m_500b.db
#paper_api_results_5m/combined_cache_session_5m_26.08_1100.db 
open_on_heat: false 
open_heat_min: 0.01   # трохи нижчий поріг
position_mode: oneway

strategy_class: strategies.greedy_breakout_universe.GreedyBreakoutUniverse
timeframe: 5m
symbols_file: universe_v5_avaai_5m_5000.txt

strategy_params:
  side: BOTH
  top_n: 8
  min_atr_ratio: 0.02
  tp_atr_mult: 3.8
  sl_atr_mult: 1.04
  max_bars_in_position: 24    # закривати через N барів (0 вимикає)
  exit_on_macd_flip: false       # 1 -> вихід при розвороті MACD (0 вимикає)
  adx_exit_threshold: 0.0    # ADX нижче порогу -> вихід (0 вимикає)
  rsi_exit_long: 45.0         # RSI нижче при лонгу -> вихід (0 вимикає)
  rsi_exit_short: 55.0        # RSI вище при шорті -> вихід (0 вимикає)
  heat_exit_threshold: 0.15   # падіння heat (0 вимикає)


portfolio:
  initial_equity: 100.0
  position_notional: 45
  max_notional_frac: 0.9

session:
  open_every_bar: true
