#!/usr/bin/env python3
"""Research-only HYPE DCA autonomous-exit replay.

This runner removes two closed-replay artifacts:
- Entry can be anchored to public 1m OHLC at/after the copy-open timestamp instead
  of Binance-copy avgCost.
- Exit is generated by deterministic TP/SL/TTL rules instead of the lead trader's
  historical close price.

No live orders, secrets, sessions, private pages, or network APIs are used.
"""
from __future__ import annotations

import argparse
import csv
import json
import math
import sys
from dataclasses import replace
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List, Sequence

import numpy as np

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from compare_binance_copy_positions_dca import read_positions  # noqa: E402
from run_hype_dca_parameter_search import (  # noqa: E402
    CANONICAL_RESEARCH_CHAMPION,
    DEFAULT_NPZ,
    DEFAULT_POSITIONS,
    DEFAULT_REPORT_DIR,
    GROUNDING_TOL,
    MIN_ORDER_USD,
    STRICT_FILL_MODE,
    Candidate,
    allocations,
    apply_candidate_slippage,
    candidate_grid,
    dca_levels,
    expand_protection_grid,
    grounding_stats,
    iso,
    leverage_stats,
    level_crossed,
    load_npz_arrays,
    ms,
    protection_threshold_pct,
    summarize,
    write_csv,
)
from telegram_signal_dca_compare import max_drawdown, ret_for  # noqa: E402


def parse_csv_floats(raw: str, *, scale: float = 1.0) -> List[float]:
    return [float(x.strip()) * scale for x in raw.split(",") if x.strip()]


def parse_csv_ints(raw: str) -> List[int]:
    return [int(float(x.strip())) for x in raw.split(",") if x.strip()]


def entry_index_for_source(t: np.ndarray, opened: datetime, entry_source: str) -> int:
    i = int(np.searchsorted(t, ms(opened), side="left"))
    if entry_source == "next_bar_open":
        i += 1
    return min(max(i, 0), len(t) - 1)


def entry_price_for_source(arrays: Dict[str, np.ndarray], idx: int, entry_source: str, fallback: float) -> float:
    if entry_source == "avgCost":
        return float(fallback)
    field = {
        "first_bar_open": "open",
        "first_bar_close": "close",
        "first_bar_high": "high",
        "first_bar_low": "low",
        "next_bar_open": "open",
    }[entry_source]
    return float(arrays[field][idx])


def exit_trigger(
    side: str,
    avg_entry: float,
    high: float,
    low: float,
    close: float,
    *,
    tp_pct: float,
    sl_pct: float,
    conservative_same_bar: bool,
) -> tuple[str | None, float | None]:
    if side == "LONG":
        tp_px = avg_entry * (1.0 + tp_pct)
        sl_px = avg_entry * (1.0 - sl_pct)
        hit_tp = high >= tp_px
        hit_sl = low <= sl_px
        if hit_tp and hit_sl:
            return ("sl_same_bar_ambiguous" if conservative_same_bar else "tp_same_bar_ambiguous"), (sl_px if conservative_same_bar else tp_px)
        if hit_sl:
            return "sl", sl_px
        if hit_tp:
            return "tp", tp_px
    else:
        tp_px = avg_entry * (1.0 - tp_pct)
        sl_px = avg_entry * (1.0 + sl_pct)
        hit_tp = low <= tp_px
        hit_sl = high >= sl_px
        if hit_tp and hit_sl:
            return ("sl_same_bar_ambiguous" if conservative_same_bar else "tp_same_bar_ambiguous"), (sl_px if conservative_same_bar else tp_px)
        if hit_sl:
            return "sl", sl_px
        if hit_tp:
            return "tp", tp_px
    return None, None


def simulate_autonomous_position(
    pos: Any,
    candidate: Candidate,
    arrays: Dict[str, np.ndarray],
    *,
    entry_source: str,
    fill_mode: str,
    tp_pct: float,
    sl_pct: float,
    ttl_hours: float,
    conservative_same_bar: bool = True,
    protection_reference_usd: float | None = None,
) -> Dict[str, Any] | None:
    t = arrays["t"]
    entry_i = entry_index_for_source(t, pos.opened, entry_source)
    horizon_ms = ms(pos.opened) + int(ttl_hours * 3600_000)
    end_i = int(np.searchsorted(t, horizon_ms, side="right"))
    end_i = min(max(end_i, entry_i + 1), len(t))
    if end_i <= entry_i:
        return None

    entry = entry_price_for_source(arrays, entry_i, entry_source, pos.entry)
    high = arrays["high"][entry_i:end_i]
    low = arrays["low"][entry_i:end_i]
    close = arrays["close"][entry_i:end_i]
    ts = t[entry_i:end_i]

    base_notional, adds = allocations(candidate)
    levels = dca_levels(pos.side, entry, candidate.steps_pct[: len(adds)])
    avg_entry = float(entry)
    notional = float(base_notional)
    fills = 0
    fill_rows: List[Dict[str, Any]] = []
    min_mtm = 0.0
    min_mtm_pct_on_notional = 0.0
    min_ok, min_leg = (min([base_notional, *adds]) >= MIN_ORDER_USD, min([base_notional, *adds]) if adds else base_notional)
    skip_boundary = fill_mode in {"touch_skip_boundary", "close_beyond_skip_boundary"}
    protection_ref = float(protection_reference_usd if protection_reference_usd is not None else candidate.target_notional)
    protection_pct = protection_threshold_pct(candidate)
    protection_loss_limit = -abs(protection_pct) * protection_ref / 100.0 if protection_pct > 0.0 else 0.0
    protection_confirm_bars = int(max(1, candidate.protection_confirm_bars))
    protection_consecutive = 0
    protection_triggered = False
    protection_trigger_reason = ""
    protection_trigger_t = 0
    protection_trigger_mtm = 0.0
    protection_trigger_mtm_pct_margin = 0.0
    protection_blocked_dca_fills = 0
    protection_blocked_dca_notional = 0.0
    blocked_probe_fill = 0
    best_after_protection_mtm = 0.0

    exit_reason = "ttl"
    exit_px = float(close[-1])
    exit_t = int(ts[-1])
    exit_i_rel = len(close) - 1

    for i in range(len(close)):
        boundary = skip_boundary and i == 0
        if protection_pct > 0.0 and not protection_triggered and not boundary:
            mark = float(low[i] if pos.side == "LONG" else high[i])
            mtm_ret = ret_for(pos.side, avg_entry, mark) - 2 * candidate.fee - 2 * candidate.slippage
            mtm = mtm_ret * notional
            if mtm <= protection_loss_limit:
                protection_consecutive += 1
            else:
                protection_consecutive = 0
            if protection_consecutive >= protection_confirm_bars:
                protection_triggered = True
                protection_trigger_reason = "adverse_mtm_blocks_dca"
                protection_trigger_t = int(ts[i])
                protection_trigger_mtm = mtm
                protection_trigger_mtm_pct_margin = 100.0 * mtm / max(protection_ref, 1e-12)
                best_after_protection_mtm = mtm

        # No same-candle fill on the entry candle for public OHLC anchors. That
        # avoids pretending we knew the full opening candle after entering.
        can_fill = not (skip_boundary and i == 0)
        if protection_triggered and can_fill:
            probe_this_candle = 0
            blocked_probe_fill = max(blocked_probe_fill, fills)
            while blocked_probe_fill < len(levels):
                touched = level_crossed(
                    pos.side,
                    low=float(low[i]),
                    high=float(high[i]),
                    close=float(close[i]),
                    level=float(levels[blocked_probe_fill]),
                    fill_mode=fill_mode,
                )
                if not touched:
                    break
                if probe_this_candle >= 1 and skip_boundary:
                    break
                protection_blocked_dca_fills += 1
                protection_blocked_dca_notional += float(adds[blocked_probe_fill])
                blocked_probe_fill += 1
                probe_this_candle += 1
            can_fill = False
        fills_this_candle = 0
        while can_fill and fills < len(levels):
            touched = level_crossed(
                pos.side,
                low=float(low[i]),
                high=float(high[i]),
                close=float(close[i]),
                level=float(levels[fills]),
                fill_mode=fill_mode,
            )
            if not touched:
                break
            if fills_this_candle >= 1 and skip_boundary:
                break
            add_notional = float(adds[fills])
            old_qty = notional / max(avg_entry, 1e-12)
            add_qty = add_notional / max(levels[fills], 1e-12)
            notional += add_notional
            avg_entry = notional / max(old_qty + add_qty, 1e-12)
            fill_rows.append({"level": levels[fills], "notional": add_notional, "t": int(ts[i])})
            fills += 1
            fills_this_candle += 1

        # MTM is marked at the adverse intrabar extreme after fills.
        mark = float(low[i] if pos.side == "LONG" else high[i])
        mtm_ret = ret_for(pos.side, avg_entry, mark) - 2 * candidate.fee - 2 * candidate.slippage
        mtm = mtm_ret * notional
        min_mtm = min(min_mtm, mtm)
        min_mtm_pct_on_notional = min(min_mtm_pct_on_notional, 100.0 * mtm / max(notional, 1e-12))
        if protection_triggered:
            favorable_mark = float(high[i] if pos.side == "LONG" else low[i])
            favorable_ret = ret_for(pos.side, avg_entry, favorable_mark) - 2 * candidate.fee - 2 * candidate.slippage
            best_after_protection_mtm = max(best_after_protection_mtm, favorable_ret * notional)

        # Exit checks also skip the entry candle under strict boundary mode.
        if skip_boundary and i == 0:
            continue
        reason, px = exit_trigger(
            pos.side,
            avg_entry,
            float(high[i]),
            float(low[i]),
            float(close[i]),
            tp_pct=tp_pct,
            sl_pct=sl_pct,
            conservative_same_bar=conservative_same_bar,
        )
        if reason is not None and px is not None:
            exit_reason = reason
            exit_px = float(px)
            exit_t = int(ts[i])
            exit_i_rel = i
            break

    gross_ret = ret_for(pos.side, avg_entry, exit_px)
    net_ret = gross_ret - 2 * candidate.fee - 2 * candidate.slippage
    pnl = net_ret * notional
    return {
        "id": pos.id,
        "symbol": pos.symbol,
        "side": pos.side,
        "opened_utc": iso(pos.opened),
        "lead_closed_utc": iso(pos.closed),
        "exit_utc": datetime.fromtimestamp(exit_t / 1000, tz=timezone.utc).isoformat().replace("+00:00", "Z"),
        "entry_source": entry_source,
        "entry": entry,
        "lead_avgCost": pos.entry,
        "lead_exit": pos.exit,
        "exit": exit_px,
        "exit_reason": exit_reason,
        "avg_entry": avg_entry,
        "notional": notional,
        "dca_fills": fills,
        "pnl": pnl,
        "net_ret_pct": 100.0 * net_ret,
        "min_mtm": min_mtm,
        "min_mtm_pct_equity": 0.0,
        "min_mtm_pct_on_notional": min_mtm_pct_on_notional,
        "min_order_usd": min_leg,
        "min_order_ok": min_ok,
        "protection_reference_usd": protection_ref,
        "protection_account_loss_stop_pct_of_margin": candidate.protection_account_loss_stop_pct_of_margin,
        "protection_floating_pnl_stop_pct_of_margin": candidate.protection_floating_pnl_stop_pct_of_margin,
        "protection_emergency_account_loss_pct_of_margin": candidate.protection_emergency_account_loss_pct_of_margin,
        "protection_confirm_bars": protection_confirm_bars,
        "protection_trigger_pct_of_margin": protection_pct,
        "protection_triggered": protection_triggered,
        "protection_trigger_reason": protection_trigger_reason,
        "protection_trigger_t": protection_trigger_t,
        "protection_trigger_mtm": protection_trigger_mtm,
        "protection_trigger_mtm_pct_margin": protection_trigger_mtm_pct_margin,
        "protection_blocked_dca_fills": protection_blocked_dca_fills,
        "protection_blocked_dca_notional": protection_blocked_dca_notional,
        "protection_post_trigger_recovery_usd": max(0.0, best_after_protection_mtm - protection_trigger_mtm) if protection_triggered else 0.0,
        "candles": int(exit_i_rel + 1),
        "ttl_hours": ttl_hours,
        "tp_pct": 100.0 * tp_pct,
        "sl_pct": 100.0 * sl_pct,
        "fill_mode": fill_mode,
        "fills_json": json.dumps(fill_rows, separators=(",", ":")),
    }


def simulate_autonomous_rows(
    positions: Sequence[Any],
    candidate: Candidate,
    arrays: Dict[str, np.ndarray],
    *,
    entry_source: str,
    fill_mode: str,
    initial_equity: float,
    position_sizing_mode: str,
    leverage: float,
    tp_pct: float,
    sl_pct: float,
    ttl_hours: float,
) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    equity = float(initial_equity)
    initial_target = float(candidate.target_notional)
    target_frac = initial_target / max(initial_equity, 1e-12)
    leverage = max(float(leverage), 1.0)
    for pos in positions:
        effective = candidate
        if position_sizing_mode == "compound":
            effective_target = min(equity * leverage, equity * target_frac)
            effective = replace(candidate, target_notional=max(effective_target, 0.0))
        row = simulate_autonomous_position(
            pos,
            effective,
            arrays,
            entry_source=entry_source,
            fill_mode=fill_mode,
            tp_pct=tp_pct,
            sl_pct=sl_pct,
            ttl_hours=ttl_hours,
            protection_reference_usd=effective.target_notional / leverage,
        )
        if row is None:
            continue
        row["initial_target_notional"] = initial_target
        row["effective_target_notional"] = effective.target_notional
        row["equity_before"] = equity
        margin_used = float(row["notional"]) / leverage
        row["leverage"] = leverage
        row["margin_used"] = margin_used
        row["min_mtm_pct_margin"] = 100.0 * float(row["min_mtm"]) / max(margin_used, 1e-12)
        row["margin_call"] = abs(float(row["min_mtm"])) >= margin_used - GROUNDING_TOL
        row["notional_gt_equity_before"] = float(row["notional"]) - equity > GROUNDING_TOL
        row["margin_used_gt_equity_before"] = margin_used - equity > GROUNDING_TOL
        equity += float(row["pnl"])
        row["equity_after"] = equity
        row["min_mtm_pct_equity"] = 100.0 * float(row.get("min_mtm", 0.0)) / max(initial_equity, 1e-12)
        rows.append(row)
    return rows


def exit_reason_counts(rows: Sequence[Dict[str, Any]]) -> str:
    counts: Dict[str, int] = {}
    for r in rows:
        counts[str(r.get("exit_reason", ""))] = counts.get(str(r.get("exit_reason", "")), 0) + 1
    return json.dumps(counts, sort_keys=True, separators=(",", ":"))


def month_splits(rows: Sequence[Dict[str, Any]], initial_equity: float) -> List[Dict[str, Any]]:
    by_month: Dict[str, List[Dict[str, Any]]] = {}
    for row in rows:
        month = str(row["exit_utc"])[:7]
        by_month.setdefault(month, []).append(row)
    out = []
    for m in sorted(by_month):
        out.append({"month": m, **summarize(by_month[m], initial_equity), "trades": len(by_month[m])})
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description="Research-only HYPE DCA autonomous TP/SL/TTL exit replay.")
    ap.add_argument("--positions-csv", default=str(DEFAULT_POSITIONS))
    ap.add_argument("--npz", default=str(DEFAULT_NPZ))
    ap.add_argument("--out-dir", default=str(DEFAULT_REPORT_DIR / "dca_autonomous_exit_grid_001"))
    ap.add_argument("--initial-equity", type=float, default=500.0)
    ap.add_argument("--slippage-bp", type=float, default=4.25)
    ap.add_argument("--entry-source", default="first_bar_open", choices=("avgCost", "first_bar_open", "first_bar_close", "first_bar_high", "first_bar_low", "next_bar_open"))
    ap.add_argument("--fill-mode", default=STRICT_FILL_MODE, choices=("touch", "touch_skip_boundary", "close_beyond", "close_beyond_skip_boundary"))
    ap.add_argument("--position-sizing-mode", choices=("fixed", "compound"), default="compound")
    ap.add_argument("--leverage", type=float, default=1.0)
    ap.add_argument("--candidate-filter", default=CANONICAL_RESEARCH_CHAMPION)
    ap.add_argument("--max-target-notional", type=float, default=500.0)
    ap.add_argument("--target-scale", type=float, default=1.0)
    ap.add_argument("--random-candidates", type=int, default=0)
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--tp-pcts", default="0.5,0.75,1.0,1.25,1.5,2.0")
    ap.add_argument("--sl-pcts", default="1.0,1.5,2.0,3.0,5.0")
    ap.add_argument("--ttl-hours", default="4,8,12,24,48,72")
    ap.add_argument(
        "--protection-grid",
        default="none,25/25/35@1,35/35/45@1,45/45/60@2",
        help="Comma grid of account/floating/emergency pct-of-margin-allocation thresholds, optionally @confirm_bars.",
    )
    ap.add_argument("--min-order-usd", type=float, default=MIN_ORDER_USD)
    ap.add_argument("--min-trade-mtm-pct", type=float, default=-50.0)
    ap.add_argument("--max-mtm-dd-pct", type=float, default=50.0)
    ap.add_argument("--topn", type=int, default=20)
    args = ap.parse_args()

    # Preserve original module behavior unless the runner is explicitly invoked.
    import run_hype_dca_parameter_search as param_mod  # noqa: E402
    param_mod.MIN_ORDER_USD = float(args.min_order_usd)
    globals()["MIN_ORDER_USD"] = float(args.min_order_usd)

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    positions = read_positions(Path(args.positions_csv))
    arrays = load_npz_arrays(Path(args.npz))

    candidates = apply_candidate_slippage(
        candidate_grid(args.target_scale, args.random_candidates, args.seed, args.max_target_notional),
        args.slippage_bp,
    )
    if args.candidate_filter:
        wanted = {x.strip() for x in args.candidate_filter.split(",") if x.strip()}
        candidates = [c for c in candidates if c.name in wanted]
        missing = wanted.difference(c.name for c in candidates)
        if missing:
            raise SystemExit(f"candidate_filter not found: {sorted(missing)}")
    candidates = expand_protection_grid(candidates, args.protection_grid)
    if not candidates:
        raise SystemExit("no candidates selected")

    tp_grid = [x / 100.0 for x in parse_csv_floats(args.tp_pcts)]
    sl_grid = [x / 100.0 for x in parse_csv_floats(args.sl_pcts)]
    ttl_grid = parse_csv_ints(args.ttl_hours)

    summaries: List[Dict[str, Any]] = []
    row_cache: Dict[str, List[Dict[str, Any]]] = {}
    for candidate in candidates:
        for tp in tp_grid:
            for sl in sl_grid:
                for ttl in ttl_grid:
                    rows = simulate_autonomous_rows(
                        positions,
                        candidate,
                        arrays,
                        entry_source=args.entry_source,
                        fill_mode=args.fill_mode,
                        initial_equity=args.initial_equity,
                        position_sizing_mode=args.position_sizing_mode,
                        leverage=args.leverage,
                        tp_pct=tp,
                        sl_pct=sl,
                        ttl_hours=ttl,
                    )
                    s = summarize(rows, args.initial_equity)
                    key = f"{candidate.name}__tp{100*tp:g}_sl{100*sl:g}_ttl{ttl:g}h".replace(".", "p")
                    s.update(
                        {
                            "key": key,
                            "candidate": candidate.name,
                            "entry_source": args.entry_source,
                            "exit_model": "tp_sl_ttl_adverse_same_bar_first",
                            "tp_pct": 100.0 * tp,
                            "sl_pct": 100.0 * sl,
                            "ttl_hours": ttl,
                            "slippage_bp_per_side": candidate.slippage * 10000.0,
                            "protection_account_loss_stop_pct_of_margin": candidate.protection_account_loss_stop_pct_of_margin,
                            "protection_floating_pnl_stop_pct_of_margin": candidate.protection_floating_pnl_stop_pct_of_margin,
                            "protection_emergency_account_loss_pct_of_margin": candidate.protection_emergency_account_loss_pct_of_margin,
                            "protection_confirm_bars": candidate.protection_confirm_bars,
                            "protection_trigger_pct_of_margin": protection_threshold_pct(candidate),
                            "protection_scale_reference": "margin_allocation_usd",
                            "fill_mode": args.fill_mode,
                            "position_sizing_mode": args.position_sizing_mode,
                            "min_order_gate_usd": MIN_ORDER_USD,
                            "exit_reason_counts": exit_reason_counts(rows),
                            "mtm_gate_ok": float(s["max_mtm_dd_pct"]) >= -abs(args.max_mtm_dd_pct),
                            "strict_trade_mtm_gate_ok": float(s["min_trade_mtm_pct_equity"]) >= float(args.min_trade_mtm_pct),
                            "min_order_gate_ok": bool(s["min_order_ok"]),
                            **grounding_stats(rows, fill_mode=args.fill_mode, min_trade_mtm_pct=args.min_trade_mtm_pct),
                            **leverage_stats(rows, leverage=args.leverage, min_trade_mtm_pct=args.min_trade_mtm_pct),
                        }
                    )
                    summaries.append(s)
                    row_cache[key] = rows

    eligible = [
        s for s in summaries
        if s["mtm_gate_ok"] and s["strict_trade_mtm_gate_ok"] and s["min_order_gate_ok"]
        and (s["grounded_compound_gate_ok"] if args.leverage <= 1.0 else s["leveraged_margin_gate_ok"])
    ]
    ranked = sorted(eligible, key=lambda s: (float(s["net_pct"]), float(s["max_mtm_dd_pct"])), reverse=True)
    all_ranked = sorted(summaries, key=lambda s: (float(s["net_pct"]), float(s["max_mtm_dd_pct"])), reverse=True)

    write_csv(out_dir / "autonomous_exit_summary_all.csv", all_ranked)
    write_csv(out_dir / "autonomous_exit_summary_eligible.csv", ranked)
    for row in ranked[: args.topn]:
        key = str(row["key"])
        safe = "".join(ch if ch.isalnum() or ch in "._-" else "_" for ch in key)
        write_csv(out_dir / "top_variants" / safe / "trades.csv", row_cache[key])
        write_csv(out_dir / "top_variants" / safe / "monthly_splits.csv", month_splits(row_cache[key], args.initial_equity))

    md = [
        "# HYPE DCA Autonomous Exit Grid",
        "",
        "Research-only. No live promotion is implied.",
        f"Entry source: `{args.entry_source}`. Exit model: TP/SL/TTL with adverse same-bar priority.",
        f"Slippage: `{args.slippage_bp:g} bp` per side. Min order gate: `${MIN_ORDER_USD:.2f}`.",
        f"Position sizing: `{args.position_sizing_mode}`, leverage diagnostic: `{args.leverage:g}x`.",
        f"Candidates: {len(candidates)}. TP grid: `{args.tp_pcts}`. SL grid: `{args.sl_pcts}`. TTL grid: `{args.ttl_hours}`.",
        f"Protection grid: `{args.protection_grid}` as account/floating/emergency pct of margin allocation; trigger blocks future DCA fills and does not force-close.",
        "",
        "| rank | candidate | protection a/f/e | confirm | tp | sl | ttl h | net % | final | max MTM DD % | min trade MTM % eq | prot hits | blocked DCA | PF | exits |",
        "|---:|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---|",
    ]
    for i, row in enumerate(ranked[: args.topn], 1):
        md.append(
            f"| {i} | {row['candidate']} | "
            f"{row['protection_account_loss_stop_pct_of_margin']:.1f}/{row['protection_floating_pnl_stop_pct_of_margin']:.1f}/{row['protection_emergency_account_loss_pct_of_margin']:.1f} | "
            f"{row['protection_confirm_bars']} | {row['tp_pct']:.2f} | {row['sl_pct']:.2f} | {row['ttl_hours']} | "
            f"{row['net_pct']:.2f} | {row['equity_end']:.2f} | {row['max_mtm_dd_pct']:.2f} | "
            f"{row['min_trade_mtm_pct_equity']:.2f} | {row['protection_trigger_count']} | "
            f"{row['protection_blocked_dca_fills']} | {row['pf']:.2f} | `{row['exit_reason_counts']}` |"
        )
    md.extend([
        "",
        "Gates:",
        f"- strict fill must be `{STRICT_FILL_MODE}`; configured `{args.fill_mode}`.",
        "- no notional over equity for unlevered compound runs; no margin-used over equity or margin calls for leveraged diagnostics.",
        f"- min trade MTM >= `{args.min_trade_mtm_pct:g}%` of initial equity.",
        f"- min leg >= `${MIN_ORDER_USD:.2f}`.",
    ])
    (out_dir / "REPORT.md").write_text("\n".join(md) + "\n", encoding="utf-8")
    (out_dir / "journal.json").write_text(
        json.dumps({"ranked_top": ranked[: args.topn], "all_count": len(summaries), "eligible_count": len(ranked)}, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(json.dumps({"out_dir": str(out_dir), "eligible_count": len(ranked), "top": ranked[:5]}, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
